name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Build web-app
        run: |
          npm ci
          npm run build && cp ./build/index.html ./build/404.html
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

          # source files (code) - /src
          # re-sources files (images, audio, videos, pdf .... files) - /public
